services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" 
    networks:
      - lic_network
    environment:
      MONGO_URI: mongodb+srv://harikrishnanvimal777:vpQG5MpODpkwIIVh@cluster0.j263u.mongodb.net/lic_DB
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  
    networks:
      - lic_network
    environment:
      REACT_APP_API_URL: http://backend:5000 

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - lic_network
    volumes:
      - mongo-data:/data/db  

networks:
  lic_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally