import mongoose from "mongoose";

const bingoSchema = new mongoose.Schema({
    num1:{
        type:Number,
        required:true,
    },
    num2:{
        type:Number,
        required:true,
    },num3:{
        type:Number,
        required:true,
    },num4:{
        type:Number,
        required:true,
    },num5:{
        type:Number,
        required:true,
    },num6:{
        type:Number,
        required:true,
    },num7:{
        type:Number,
        required:true,
    },num8:{
        type:Number,
        required:true,
    },num9:{
        type:Number,
        required:true,
    },num10:{
        type:Number,
        required:true,
    },num11:{
        type:Number,
        required:true,
    },num12:{
        type:Number,
        required:true,
    },num13:{
        type:Number,
        required:true,
    },num14:{
        type:Number,
        required:true,
    },num15:{
        type:Number,
        required:true,
    },num16:{
        type:Number,
        required:true,
    },num17:{
        type:Number,
        required:true,
    },num18:{
        type:Number,
        required:true,
    },num19:{
        type:Number,
        required:true,
    },num20:{
        type:Number,
        required:true,
    },num21:{
        type:Number,
        required:true,
    },num22:{
        type:Number,
        required:true,
    },num23:{
        type:Number,
        required:true,
    },num24:{
        type:Number,
        required:true,
    },num25:{
        type:Number,
        required:true,
    },
    isVerified:{
        type:Boolean,
        default:false
    }
});

export const Bingo = mongoose.model("Bingo",bingoSchema);